name: Release

on:
  push:
    tags: ['v*']
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - target: x86_64-apple-darwin
            os: macOS-13
          - target: aarch64-apple-darwin
            os: macOS-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm

    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          repository: goccy/bigquery-emulator
          ref: ${{ github.ref_name }}

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24'
          cache: true

      - run: go build -ldflags="-s -w" -trimpath -o bigquery-emulator-${{ matrix.platform.target }} ./cmd/bigquery-emulator
        env:
          CGO_ENABLED: 1
          CXX: clang++

      - run: ./bigquery-emulator-${{ matrix.platform.target }} -h
      - run: tar -czf bigquery-emulator-${{ matrix.platform.target }}.tar.gz bigquery-emulator-${{ matrix.platform.target }}

      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            bigquery-emulator-${{ matrix.platform.target }}.tar.gz

